[server]
# Increase upload limit to 400MB for large documents
maxUploadSize = 400

# Disable file watcher to improve performance and avoid torch issues
fileWatcherType = "none"

# Disable headless mode warnings
headless = true

# Performance optimizations
enableCORS = false
enableXsrfProtection = false

[browser]
# Disable usage stats collection
gatherUsageStats = false

[theme]
# Use light theme for better performance
base = "light"

[logger]
# Reduce logging verbosity
level = "error"

[client]
# Disable toolbar for cleaner UI
toolbarMode = "minimal" 