[server]
# Set maximum upload size to 200MB (default is 200MB, but being explicit)
# This allows for large PDFs including 19-page documents
maxUploadSize = 200

# Enable file watching for development
fileWatcherType = "auto"

# Set port
port = 8501

[browser]
# Automatically open browser when starting
gatherUsageStats = false

[theme]
# Optional: Set theme colors
primaryColor = "#1F497D"  # Norstella Blue
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730" 