[server]
# Set maximum upload size to 200MB
maxUploadSize = 200

# Increase message size for large uploads
maxMessageSize = 200

# Disable deep module watching to prevent torch.classes errors
fileWatcherType = "none"

# Set port
port = 8501

# Disable XSRF protection to allow CORS (fixes the warning)
enableXsrfProtection = false

[browser]
# Don't gather usage stats
gatherUsageStats = false

[theme]
# Norstella brand colors
primaryColor = "#1F497D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730" 